name: Integration
on:
  push:
    branches:
      - main
jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: $ {{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys:
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: yarn list

      - name: Install dependencies
        run: yarn install
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   needs: preparation
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install deps
  #       run: yarn install
  #     - name: Run linter
  #       run: yarn lint
  # build_test:
  #   name: Test build project
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - lint
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install deps
  #       run: yarn install
  #     - name: Build project
  #       run: yarn build