name: Integration
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: yarn install
      - name: Run linter
        run: yarn lint
  build_test:
    name: Test build project
    runs-on: ubuntu-latest
    needs: 
      - lint
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: yarn install
      - name: Build project
        run: yarn build