name: Integration
on:
  push:
    branches:
      - main
jobs:
  preparation:
    name: Prepare dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
  # preparation:
  #   name: Prepare dependencies
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cache node_modules
  #       id: cache-npm
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         # npm cache files are stored in `~/.npm` on Linux/macOS
  #         path: ~/.npm
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          # restore-keys: |
          #   ${{ runner.os }}-build-${{ env.cache-name }}-
          #   ${{ runner.os }}-build-
          #   ${{ runner.os }}-
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   needs: preparation
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install deps
  #       run: yarn install
  #     - name: Run linter
  #       run: yarn lint
  # build_test:
  #   name: Test build project
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - lint
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install deps
  #       run: yarn install
  #     - name: Build project
  #       run: yarn build